import { Router } from 'express'
import { Role } from '@prisma/client'
import { z } from 'zod'
import { prisma } from '../config/prisma.js'
import { authenticate, authorize } from '../middleware/auth.js'
import { asyncHandler } from '../utils/async.js'
import { AppError } from '../utils/errors.js'

export const adminRouter = Router()
adminRouter.use(authenticate, authorize(Role.ADMIN, Role.SUPER_ADMIN))
const audit = (adminId: string, action: string, entity: string, entityId?: string, metadata?: object) => prisma.auditLog.create({ data: { adminId, action, entity, entityId, metadata } })

adminRouter.get('/dashboard', asyncHandler(async (_req, res) => {
  const today = new Date(); today.setHours(0,0,0,0)
  const [revenue, todayRevenue, orders, customers, products, lowStock, pendingOrders, recentOrders] = await Promise.all([
    prisma.order.aggregate({ where: { paymentStatus: 'PAID' }, _sum: { total: true } }), prisma.order.aggregate({ where: { paymentStatus: 'PAID', createdAt: { gte: today } }, _sum: { total: true } }), prisma.order.count(), prisma.user.count({ where: { role: 'CUSTOMER' } }), prisma.product.count({ where: { status: 'ACTIVE' } }), prisma.product.count({ where: { stockQuantity: { lte: 5 }, trackInventory: true } }), prisma.order.count({ where: { status: 'PENDING' } }), prisma.order.findMany({ take: 8, orderBy: { createdAt: 'desc' }, include: { user: { select: { firstName: true, lastName: true, email: true } } } })
  ])
  res.json({ success: true, data: { kpis: { todayRevenue: todayRevenue._sum.total ?? 0, totalRevenue: revenue._sum.total ?? 0, orders, customers, products, lowStock, pendingOrders, averageOrderValue: orders ? Number(revenue._sum.total ?? 0) / orders : 0 }, recentOrders } })
}))

const productInput = z.object({ name: z.string().min(2), slug: z.string().regex(/^[a-z0-9-]+$/), sku: z.string().min(2), description: z.string().min(10), shortDescription: z.string().optional(), categoryId: z.string(), brandId: z.string(), price: z.number().positive(), compareAtPrice: z.number().positive().optional(), costPrice: z.number().positive().optional(), stockQuantity: z.number().int().nonnegative(), lowStockThreshold: z.number().int().nonnegative().default(5), status: z.enum(['DRAFT','ACTIVE','ARCHIVED']).default('DRAFT'), isActive: z.boolean().default(true), isFeatured: z.boolean().default(false), isNewArrival: z.boolean().default(false), isBestSeller: z.boolean().default(false), ingredients: z.string().optional(), benefits: z.string().optional(), howToUse: z.string().optional(), skinType: z.array(z.string()).default([]), hairType: z.array(z.string()).default([]), concerns: z.array(z.string()).default([]), size: z.string().optional(), weight: z.number().int().positive().optional(), seoTitle: z.string().optional(), seoDescription: z.string().optional(), images: z.array(z.object({ url: z.string().url(), altText: z.string(), sortOrder: z.number().int().default(0) })).min(1), variants: z.array(z.object({ name:z.string().min(1), sku:z.string().min(2), price:z.number().positive().optional(), stockQuantity:z.number().int().nonnegative(), attributes:z.record(z.string(),z.string()), image:z.string().url().optional(), isActive:z.boolean().default(true) })).default([]) })
adminRouter.get('/products', asyncHandler(async (req, res) => { const search = z.string().optional().parse(req.query.search); res.json({ success: true, data: await prisma.product.findMany({ where: search ? { OR: [{ name: { contains: search, mode: 'insensitive' } }, { sku: { contains: search, mode: 'insensitive' } }] } : undefined, include: { category: true, brand: true, images: true }, orderBy: { createdAt: 'desc' } }) }) }))
adminRouter.get('/products/:id',asyncHandler(async(req,res)=>{const product=await prisma.product.findUnique({where:{id:String(req.params.id)},include:{images:{orderBy:{sortOrder:'asc'}},variants:true,category:true,brand:true}});if(!product)throw new AppError(404,'Product not found.');res.json({success:true,data:product})}))
adminRouter.post('/products', asyncHandler(async (req, res) => { const input = productInput.parse(req.body); const { images, variants, ...data } = input; const product = await prisma.product.create({ data: { ...data, images: { create: images }, variants:{create:variants} }, include: { images: true,variants:true } }); await audit(req.user!.id, 'product.created', 'Product', product.id); res.status(201).json({ success: true, data: product }) }))
adminRouter.patch('/products/:id', asyncHandler(async (req, res) => { const input = productInput.partial().parse(req.body); const { images, variants, ...data } = input; const product = await prisma.$transaction(async tx => { if (images) { await tx.productImage.deleteMany({ where: { productId: String(req.params.id) } }); await tx.productImage.createMany({ data: images.map(image => ({ ...image, productId: String(req.params.id) })) }) } if(variants){await tx.productVariant.deleteMany({where:{productId:String(req.params.id)}});if(variants.length)await tx.productVariant.createMany({data:variants.map(variant=>({...variant,productId:String(req.params.id)}))})} return tx.product.update({ where: { id: String(req.params.id) }, data, include: { images: true,variants:true } }) }); await audit(req.user!.id, 'product.updated', 'Product', product.id); res.json({ success: true, data: product }) }))
adminRouter.delete('/products/:id', asyncHandler(async (req, res) => { await prisma.product.update({ where: { id: String(req.params.id) }, data: { status: 'ARCHIVED', isActive: false } }); await audit(req.user!.id, 'product.archived', 'Product', String(req.params.id)); res.status(204).end() }))
adminRouter.get('/orders', asyncHandler(async (req, res) => { const status = z.enum(['PENDING','CONFIRMED','PROCESSING','PACKED','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED','REFUNDED']).optional().parse(req.query.status); res.json({ success: true, data: await prisma.order.findMany({ where: { status }, include: { user: { select: { firstName: true, lastName: true, email: true } }, items: true, payments: true }, orderBy: { createdAt: 'desc' } }) }) }))
adminRouter.patch('/orders/:id/status', asyncHandler(async (req, res) => { const { status, note } = z.object({ status: z.enum(['PENDING','CONFIRMED','PROCESSING','PACKED','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED','REFUNDED']), note: z.string().optional() }).parse(req.body); const order = await prisma.order.update({ where: { id: String(req.params.id) }, data: { status, statusHistory: { create: { status, note } } }, include: { statusHistory: true } }); await audit(req.user!.id, 'order.status_updated', 'Order', order.id, { status }); res.json({ success: true, data: order }) }))
adminRouter.post('/inventory/:productId', asyncHandler(async (req, res) => { const input = z.object({ variantId: z.string().optional(), quantity: z.number().int(), type: z.enum(['PURCHASE','SALE','RETURN','RESTOCK','ADJUSTMENT']), reference: z.string().optional(), notes: z.string().optional() }).parse(req.body); const result = await prisma.$transaction(async tx => { if (input.variantId) { const current = await tx.productVariant.findUnique({ where: { id: input.variantId } }); if (!current) throw new AppError(404, 'Variant not found.'); const next = current.stockQuantity + input.quantity; if (next < 0) throw new AppError(409, 'Stock cannot go below zero.'); await tx.productVariant.update({ where: { id: current.id }, data: { stockQuantity: next } }); return tx.inventoryMovement.create({ data: { ...input, productId: String(req.params.productId), previousStock: current.stockQuantity, newStock: next, createdBy: req.user!.id } }) } const current = await tx.product.findUnique({ where: { id: String(req.params.productId) } }); if (!current) throw new AppError(404, 'Product not found.'); const next = current.stockQuantity + input.quantity; if (next < 0) throw new AppError(409, 'Stock cannot go below zero.'); await tx.product.update({ where: { id: current.id }, data: { stockQuantity: next } }); return tx.inventoryMovement.create({ data: { ...input, productId: current.id, previousStock: current.stockQuantity, newStock: next, createdBy: req.user!.id } }) }); await audit(req.user!.id, 'inventory.adjusted', 'Product', String(req.params.productId), input); res.status(201).json({ success: true, data: result }) }))
adminRouter.get('/inventory',asyncHandler(async(_req,res)=>res.json({success:true,data:await prisma.product.findMany({select:{id:true,name:true,sku:true,stockQuantity:true,lowStockThreshold:true,trackInventory:true,variants:{select:{id:true,name:true,sku:true,stockQuantity:true}},inventoryMovements:{take:5,orderBy:{createdAt:'desc'}}},orderBy:{name:'asc'}})})))
adminRouter.get('/customers', asyncHandler(async (_req, res) => res.json({ success: true, data: await prisma.user.findMany({ where: { role: 'CUSTOMER' }, select: { id: true, firstName: true, lastName: true, email: true, phone: true, status: true, createdAt: true, _count: { select: { orders: true } }, orders: { where: { paymentStatus: 'PAID' }, select: { total: true } } } }) })))
adminRouter.get('/payments', asyncHandler(async (_req, res) => res.json({ success: true, data: await prisma.payment.findMany({ include: { order: { select: { orderNumber: true } }, user: { select: { firstName: true, lastName: true, email: true } } }, orderBy: { createdAt: 'desc' } }) })))
adminRouter.get('/reviews', asyncHandler(async (_req, res) => res.json({ success: true, data: await prisma.review.findMany({ include: { product: { select: { name: true } }, user: { select: { firstName: true, lastName: true } } }, orderBy: { createdAt: 'desc' } }) })))
adminRouter.patch('/reviews/:id', asyncHandler(async (req, res) => { const { status } = z.object({ status: z.enum(['PENDING','APPROVED','HIDDEN']) }).parse(req.body); res.json({ success: true, data: await prisma.review.update({ where: { id: String(req.params.id) }, data: { status } }) }) }))
adminRouter.delete('/reviews/:id',asyncHandler(async(req,res)=>{await prisma.review.delete({where:{id:String(req.params.id)}});res.status(204).end()}))
adminRouter.get('/categories',asyncHandler(async(_req,res)=>res.json({success:true,data:await prisma.category.findMany({orderBy:{sortOrder:'asc'}})})))
adminRouter.post('/categories',asyncHandler(async(req,res)=>{const data=z.object({name:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/),description:z.string().optional(),image:z.string().url().optional(),sortOrder:z.number().int().default(0)}).parse(req.body);const item=await prisma.category.create({data});await audit(req.user!.id,'category.created','Category',item.id);res.status(201).json({success:true,data:item})}))
adminRouter.patch('/categories/:id',asyncHandler(async(req,res)=>{const data=z.object({name:z.string().min(2).optional(),description:z.string().optional(),image:z.string().url().optional(),isActive:z.boolean().optional(),sortOrder:z.number().int().optional()}).parse(req.body);const item=await prisma.category.update({where:{id:String(req.params.id)},data});res.json({success:true,data:item})}))
adminRouter.get('/brands',asyncHandler(async(_req,res)=>res.json({success:true,data:await prisma.brand.findMany({orderBy:{name:'asc'}})})))
adminRouter.post('/brands',asyncHandler(async(req,res)=>{const data=z.object({name:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/),description:z.string().optional(),logo:z.string().url().optional()}).parse(req.body);const item=await prisma.brand.create({data});await audit(req.user!.id,'brand.created','Brand',item.id);res.status(201).json({success:true,data:item})}))
adminRouter.patch('/brands/:id',asyncHandler(async(req,res)=>{const data=z.object({name:z.string().min(2).optional(),description:z.string().optional(),logo:z.string().url().optional(),isActive:z.boolean().optional()}).parse(req.body);res.json({success:true,data:await prisma.brand.update({where:{id:String(req.params.id)},data})})}))
adminRouter.get('/coupons',asyncHandler(async(_req,res)=>res.json({success:true,data:await prisma.coupon.findMany({orderBy:{createdAt:'desc'}})})))
adminRouter.post('/coupons',asyncHandler(async(req,res)=>{const data=z.object({code:z.string().min(3).transform(v=>v.toUpperCase()),description:z.string().optional(),type:z.enum(['PERCENTAGE','FIXED_AMOUNT']),value:z.number().positive(),minimumSpend:z.number().nonnegative().optional(),maximumDiscount:z.number().positive().optional(),usageLimit:z.number().int().positive().optional(),startsAt:z.coerce.date().optional(),expiresAt:z.coerce.date().optional()}).parse(req.body);const item=await prisma.coupon.create({data});await audit(req.user!.id,'coupon.created','Coupon',item.id);res.status(201).json({success:true,data:item})}))
adminRouter.patch('/coupons/:id',asyncHandler(async(req,res)=>{const data=z.object({description:z.string().optional(),value:z.number().positive().optional(),minimumSpend:z.number().nonnegative().optional(),maximumDiscount:z.number().positive().optional(),usageLimit:z.number().int().positive().optional(),expiresAt:z.coerce.date().optional(),isActive:z.boolean().optional()}).parse(req.body);res.json({success:true,data:await prisma.coupon.update({where:{id:String(req.params.id)},data})})}))
adminRouter.get('/delivery',asyncHandler(async(_req,res)=>res.json({success:true,data:await prisma.deliveryZone.findMany({orderBy:{county:'asc'}})})))
adminRouter.post('/delivery',asyncHandler(async(req,res)=>{const data=z.object({name:z.string().min(2),county:z.string().min(2),town:z.string().optional(),fee:z.number().nonnegative(),freeDeliveryThreshold:z.number().nonnegative().optional(),estimatedDays:z.string().min(2)}).parse(req.body);res.status(201).json({success:true,data:await prisma.deliveryZone.create({data})})}))
adminRouter.patch('/delivery/:id',asyncHandler(async(req,res)=>{const data=z.object({name:z.string().min(2).optional(),county:z.string().min(2).optional(),town:z.string().optional(),fee:z.number().nonnegative().optional(),freeDeliveryThreshold:z.number().nonnegative().optional(),estimatedDays:z.string().min(2).optional(),isActive:z.boolean().optional()}).parse(req.body);res.json({success:true,data:await prisma.deliveryZone.update({where:{id:String(req.params.id)},data})})}))
adminRouter.get('/messages',asyncHandler(async(_req,res)=>res.json({success:true,data:await prisma.contactMessage.findMany({orderBy:{createdAt:'desc'}})})))
adminRouter.patch('/messages/:id',asyncHandler(async(req,res)=>{const {status}=z.object({status:z.enum(['NEW','READ','RESOLVED'])}).parse(req.body);res.json({success:true,data:await prisma.contactMessage.update({where:{id:String(req.params.id)},data:{status}})})}))
adminRouter.get('/newsletter',asyncHandler(async(_req,res)=>res.json({success:true,data:await prisma.newsletterSubscriber.findMany({orderBy:{createdAt:'desc'}})})))
adminRouter.get('/settings', asyncHandler(async (_req, res) => {
  const settings = await prisma.storeSetting.findUnique({ where: { id: 'store' } })
  res.json({ success: true, data: settings })
}))
adminRouter.get('/banners',asyncHandler(async(_req,res)=>res.json({success:true,data:await prisma.banner.findMany({orderBy:{createdAt:'desc'}})})))
adminRouter.post('/banners',asyncHandler(async(req,res)=>{const data=z.object({title:z.string().min(2),subtitle:z.string().optional(),image:z.string().url(),mobileImage:z.string().url().optional(),ctaText:z.string().optional(),ctaUrl:z.string().optional(),position:z.string().default('HOME_HERO'),startsAt:z.coerce.date().optional(),endsAt:z.coerce.date().optional()}).parse(req.body);res.status(201).json({success:true,data:await prisma.banner.create({data})})}))
adminRouter.patch('/banners/:id',asyncHandler(async(req,res)=>{const data=z.object({title:z.string().min(2).optional(),subtitle:z.string().optional(),image:z.string().url().optional(),mobileImage:z.string().url().optional(),ctaText:z.string().optional(),ctaUrl:z.string().optional(),position:z.string().optional(),isActive:z.boolean().optional(),startsAt:z.coerce.date().optional(),endsAt:z.coerce.date().optional()}).parse(req.body);res.json({success:true,data:await prisma.banner.update({where:{id:String(req.params.id)},data})})}))
adminRouter.get('/analytics',asyncHandler(async(_req,res)=>{const [sales,ordersByStatus,topProducts,growth]=await Promise.all([prisma.order.groupBy({by:['createdAt'],where:{paymentStatus:'PAID'},_sum:{total:true},_count:true,orderBy:{createdAt:'asc'}}),prisma.order.groupBy({by:['status'],_count:true}),prisma.orderItem.groupBy({by:['productId','productName'],_sum:{quantity:true,total:true},orderBy:{_sum:{quantity:'desc'}},take:10}),prisma.user.groupBy({by:['createdAt'],where:{role:'CUSTOMER'},_count:true,orderBy:{createdAt:'asc'}})]);res.json({success:true,data:{sales,ordersByStatus,topProducts,customerGrowth:growth}})}))
adminRouter.get('/admins',asyncHandler(async(_req,res)=>res.json({success:true,data:await prisma.user.findMany({where:{role:{in:['ADMIN','SUPER_ADMIN']}},select:{id:true,firstName:true,lastName:true,email:true,role:true,status:true,createdAt:true}})})))
adminRouter.post('/admins',authorize(Role.SUPER_ADMIN),asyncHandler(async(req,res)=>{const bcrypt=await import('bcryptjs');const data=z.object({firstName:z.string().min(2),lastName:z.string().min(2),email:z.string().email().transform(v=>v.toLowerCase()),password:z.string().min(10),role:z.enum(['ADMIN','SUPER_ADMIN']).default('ADMIN')}).parse(req.body);const admin=await prisma.user.create({data:{firstName:data.firstName,lastName:data.lastName,email:data.email,passwordHash:await bcrypt.hash(data.password,12),role:data.role,emailVerified:true},select:{id:true,firstName:true,lastName:true,email:true,role:true,status:true}});await audit(req.user!.id,'admin.created','User',admin.id);res.status(201).json({success:true,data:admin})}))
adminRouter.delete('/categories/:id',asyncHandler(async(req,res)=>{const id=String(req.params.id);await prisma.category.update({where:{id},data:{isActive:false}});await audit(req.user!.id,'category.archived','Category',id);res.status(204).end()}))
adminRouter.delete('/brands/:id',asyncHandler(async(req,res)=>{const id=String(req.params.id);await prisma.brand.update({where:{id},data:{isActive:false}});await audit(req.user!.id,'brand.archived','Brand',id);res.status(204).end()}))
adminRouter.delete('/coupons/:id',asyncHandler(async(req,res)=>{await prisma.coupon.update({where:{id:String(req.params.id)},data:{isActive:false}});res.status(204).end()}))
adminRouter.delete('/delivery/:id',asyncHandler(async(req,res)=>{await prisma.deliveryZone.update({where:{id:String(req.params.id)},data:{isActive:false}});res.status(204).end()}))
adminRouter.delete('/messages/:id',asyncHandler(async(req,res)=>{await prisma.contactMessage.delete({where:{id:String(req.params.id)}});res.status(204).end()}))
adminRouter.delete('/banners/:id',asyncHandler(async(req,res)=>{await prisma.banner.delete({where:{id:String(req.params.id)}});res.status(204).end()}))
adminRouter.patch('/settings',asyncHandler(async(req,res)=>{const data=z.object({storeName:z.string().optional(),tagline:z.string().optional(),contactEmail:z.string().email().optional(),phone:z.string().optional(),whatsapp:z.string().optional(),freeDeliveryThreshold:z.number().optional(),defaultDeliveryFee:z.number().optional(),supportHours:z.string().optional()}).parse(req.body);res.json({success:true,data:await prisma.storeSetting.upsert({where:{id:'store'},create:{id:'store',...data},update:data})})}))


