import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../config/prisma.js'
import { authenticate } from '../middleware/auth.js'
import { asyncHandler } from '../utils/async.js'
import { AppError } from '../utils/errors.js'

export const contentRouter = Router()
contentRouter.post('/newsletter', asyncHandler(async (req, res) => { const { email } = z.object({ email: z.string().email().transform(v => v.toLowerCase()) }).parse(req.body); const subscriber = await prisma.newsletterSubscriber.upsert({ where: { email }, create: { email }, update: { isActive: true } }); res.status(201).json({ success: true, data: subscriber }) }))
contentRouter.post('/contact', asyncHandler(async (req, res) => { const data = z.object({ name: z.string().min(2), email: z.string().email(), phone: z.string().optional(), subject: z.string().min(3), message: z.string().min(10).max(3000) }).parse(req.body); const message = await prisma.contactMessage.create({ data }); res.status(201).json({ success: true, data: { id: message.id } }) }))
contentRouter.post('/reviews', authenticate, asyncHandler(async (req, res) => { const data = z.object({ productId: z.string(), rating: z.number().int().min(1).max(5), title: z.string().min(2), comment: z.string().min(10).max(2000) }).parse(req.body); const purchased = await prisma.orderItem.findFirst({ where: { productId: data.productId, order: { userId: req.user!.id, status: 'DELIVERED' } } }); if (!purchased) throw new AppError(403, 'Reviews are available after a verified purchase.'); const review = await prisma.review.upsert({ where: { productId_userId: { productId: data.productId, userId: req.user!.id } }, create: { ...data, userId: req.user!.id, isVerifiedPurchase: true }, update: { rating: data.rating, title: data.title, comment: data.comment, status: 'PENDING' } }); res.status(201).json({ success: true, data: review }) }))
contentRouter.post('/coupons/validate', asyncHandler(async (req, res) => { const { code, subtotal } = z.object({ code: z.string(), subtotal: z.number().nonnegative() }).parse(req.body); const now = new Date(); const coupon = await prisma.coupon.findUnique({ where: { code: code.toUpperCase() } }); if (!coupon) throw new AppError(400, 'Invalid coupon.'); if (!coupon.isActive || (coupon.startsAt && coupon.startsAt > now) || (coupon.expiresAt && coupon.expiresAt < now) || (coupon.usageLimit != null && coupon.usageCount >= coupon.usageLimit)) throw new AppError(400, 'Expired coupon.'); if (coupon.minimumSpend && subtotal < Number(coupon.minimumSpend)) throw new AppError(400, 'Your bag does not meet the minimum spend for this coupon.'); let discount = coupon.type === 'PERCENTAGE' ? subtotal * Number(coupon.value) / 100 : Number(coupon.value); if (coupon.maximumDiscount) discount = Math.min(discount, Number(coupon.maximumDiscount)); res.json({ success: true, data: { code: coupon.code, discount: Math.min(discount, subtotal) } }) }))
contentRouter.get('/delivery-zones', asyncHandler(async (_req, res) => { const [zones, settings] = await Promise.all([prisma.deliveryZone.findMany({ where: { isActive: true }, orderBy: [{ county: 'asc' }, { town: 'asc' }] }), prisma.storeSetting.findUnique({ where: { id: 'store' } })]); res.json({ success: true, data: [{ id: 'PICKUP', name: 'Pick up at MYOKIN shop', county: 'MYOKIN', town: null, fee: 0, estimatedDays: 'Ready for collection' }, ...zones, { id: 'BASE_DELIVERY', name: 'My area is not listed — delivery pending approval', county: 'Pending approval', town: null, fee: Number(settings?.defaultDeliveryFee ?? 0), estimatedDays: 'To be confirmed by MYOKIN' }] }) }))

